Monkey-patch so we're using greenthreads instead of real ones
I'm a little unclear on *why* exactly, but now that hashes are
consolidated in a separate process, the eventlet hub keeps bombing
out with

    error: cannot switch to a different thread

Monkey-patching seems to fix it.